/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import configDB.crud_jadwal_sidang; // Import kelas CRUD yang sesuai
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frame_jadwal_sidang extends javax.swing.JFrame {

    private crud_jadwal_sidang objekKu; // Objek CRUD

    /**
     * Creates new form frame_jadwal_sidang
     */
    public frame_jadwal_sidang() {
        initComponents();
        this.setLocationRelativeTo(null);
        objekKu = new crud_jadwal_sidang(); // Inisialisasi objek
        // Tampilkan data saat frame pertama kali dibuka
        objekKu.tampilDataJadwalSidang(tableJadwalSidang, "select * from jadwal_sidang");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        txtSusunanMajlis = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJadwalSidang = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAcara = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRuang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelola Jadwal Sidang");

        jLabel1.setText("ID Jadwal");

        jLabel2.setText("Tanggal (YYYY-MM-DD)");

        jLabel3.setText("Jam (HH:MM:SS)");

        jLabel4.setText("Susunan Majlis");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tableJadwalSidang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tableJadwalSidang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJadwalSidangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableJadwalSidang);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        jLabel5.setText("Acara");

        jLabel6.setText("Ruang");

        jLabel7.setText("Hari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHapus)
                                .addGap(31, 31, 31)
                                .addComponent(btnTambah)
                                .addGap(37, 37, 37)
                                .addComponent(btnUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtId)
                                    .addComponent(txtJam)
                                    .addComponent(txtSusunanMajlis)
                                    .addComponent(txtAcara)
                                    .addComponent(txtRuang)
                                    .addComponent(txtHari))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCari)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSusunanMajlis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAcara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            // Validasi input (contoh sederhana)
            if (txtHari.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Hari belum diisi");
                txtHari.requestFocus();
            } else if (txtTanggal.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tanggal belum diisi");
                txtTanggal.requestFocus();
            } else if (txtJam.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Jam belum diisi");
                txtJam.requestFocus();
            } else if (txtAcara.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Acara belum diisi");
                txtAcara.requestFocus();
            } else {
                // Panggil metode simpan dari kelas CRUD
                objekKu.simpanJadwalSidang02(
                        txtHari.getText(),
                        txtTanggal.getText(),
                        txtJam.getText(),
                        txtSusunanMajlis.getText(),
                        txtAcara.getText(),
                        txtRuang.getText()
                );
                // Refresh tabel
                objekKu.tampilDataJadwalSidang(tableJadwalSidang, "select * from jadwal_sidang");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (txtId.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID Jadwal belum diisi (Pilih data dari tabel)");
                txtId.requestFocus();
            } else {
                // Panggil metode ubah dari kelas CRUD
                objekKu.ubahJadwalSidang02(
                        txtId.getText(),
                        txtHari.getText(),
                        txtTanggal.getText(),
                        txtJam.getText(),
                        txtSusunanMajlis.getText(),
                        txtAcara.getText(),
                        txtRuang.getText()
                );
                // Refresh tabel
                objekKu.tampilDataJadwalSidang(tableJadwalSidang, "select * from jadwal_sidang");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            if (txtId.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID Jadwal belum diisi (Pilih data dari tabel)");
                txtId.requestFocus();
            } else {
                // Panggil metode hapus dari kelas CRUD
                objekKu.hapusJadwalSidang02(txtId.getText());
                
                // Kosongkan form
                txtId.setText(null);
                txtHari.setText(null);
                txtTanggal.setText(null);
                txtJam.setText(null);
                txtSusunanMajlis.setText(null);
                txtAcara.setText(null);
                txtRuang.setText(null);
                
                // Refresh tabel
                objekKu.tampilDataJadwalSidang(tableJadwalSidang, "select * from jadwal_sidang");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // Fungsi pencarian (live search)
        String cari = "select * from jadwal_sidang where Hari like '%" + txtCari.getText() + "%'"
                + " OR Acara like '%" + txtCari.getText() + "%' "
                + " OR Ruang like '%" + txtCari.getText() + "%' "
                + " OR Susunan_Majlis like '%" + txtCari.getText() + "%' ";
        objekKu.tampilDataJadwalSidang(tableJadwalSidang, cari);
    }//GEN-LAST:event_txtCariKeyPressed

    private void tableJadwalSidangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJadwalSidangMouseClicked
        // Mengisi form saat data di tabel di-klik
        int baris = tableJadwalSidang.rowAtPoint(evt.getPoint());
        String id = tableJadwalSidang.getValueAt(baris, 0).toString();
        String hari = tableJadwalSidang.getValueAt(baris, 1).toString();
        String tanggal = tableJadwalSidang.getValueAt(baris, 2).toString();
        String jam = tableJadwalSidang.getValueAt(baris, 3).toString();
        String susunan = tableJadwalSidang.getValueAt(baris, 4).toString();
        String acara = tableJadwalSidang.getValueAt(baris, 5).toString();
        String ruang = tableJadwalSidang.getValueAt(baris, 6).toString();
        
        txtId.setText(id);
        txtHari.setText(hari);
        txtTanggal.setText(tanggal);
        txtJam.setText(jam);
        txtSusunanMajlis.setText(susunan);
        txtAcara.setText(acara);
        txtRuang.setText(ruang);
    }//GEN-LAST:event_tableJadwalSidangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_jadwal_sidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_jadwal_sidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_jadwal_sidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_jadwal_sidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_jadwal_sidang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableJadwalSidang;
    private javax.swing.JTextField txtAcara;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHari;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtRuang;
    private javax.swing.JTextField txtSusunanMajlis;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}